name: Transport CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: 3.9

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10 #${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10 #${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt; 
        # if [ -f requirements.txt ]; then 
        #   pip install -r requirements.txt
        else
          pip install django django-crispy-forms crispy-bootstrap5
        fi

    - name: Run migrations
      run: python manage.py migrate

    - name: Run server
      run: python manage.py runserver
